title: SZZ materiály
description: Digitální rozcestník studijních materiálů pro státní závěrečné zkoušky.
remote_theme: mmistakes/minimal-mistakes
repository: ondrejsvorc/SZZ

url: "https://szz.ondrejsvorc.cz"
baseurl: "" 

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - .git
  - .cursor
  - vendor
  - pipeline.yml
  - generate_index.py
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules